version: "3"

services:
  speedtest:
    build:
      network: host
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - FIREBASE_DATABASE_URL=${FIREBASE_DATABASE_URL}
      - PROJECT_ID=${PROJECT_ID}
      - PRIVATE_KEY_ID=${PRIVATE_KEY_ID}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - CLIENT_EMAIL=${CLIENT_EMAIL}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_X509_CERT_URL=${CLIENT_X509_CERT_URL}
    network_mode: host